### ISSUE TITLE
Please revert or fix "Don't delay Firefox startup"

### ISSUE THREAD

**Issue by nelegalno** [Pale-Moon-Addons-Team/adblock-latitude#1]
Due to the `Don't delay Firefox startup` ( https://github.com/binoc-software/adblock-latitude/commit/bf8d678dacdf804614da894ad2a18ee3a3afd64e ) change now we are seeing ads even with the `extensions.adblockplus.please_kill_startup_performance` option enabled.
I was hoping you wouldn't implement it but since it's in could you revert the change until it is fixed or find a way to return the security part of ABP in ABL. One of the main reasons I used ABP was for it's privacy and security enhancements rather than its ability to block AD's and if I have to "sacrifice" few second's each time PaleMoon starts I'd rather do that than have to waste much more reloading 40+ tabs each time and having no privacy and security enhancements at startup.

More info on the subject:
https://issues.adblockplus.org/ticket/549
https://issues.adblockplus.org/ticket/418
https://adblockplus.org/forum/viewtopic.php?f=1&t=22906

**Comment by mattatobin** [comment]
This is causing issues on upgrade. I am reverting this for the time being and releasing an emergency update as 3.0.2

**Comment by nelegalno** [comment]
Haven't noticed problems when I installed the 3.0.1pre or updated it to 3.0.1.

**Comment by wolfbeast** [comment]
Seems bootstrapping is still a problem in 3.0.2 on upgrade, at least on fast machines -- likely a timing issue or potential race condition in the ABP bootstrap code somewhere.

We're looking into removing the whole bootstrap thing instead for the next big update of ABL, to avoid these issues 9and the inherent delay of the SDK needing the startup pref, to begin with)

**Comment by mattatobin** [comment]
This issue is moot in the Next Generation ABL

Resolving as WONTFIX
