### ISSUE TITLE
[Request] YouTube channel whitelist feature for AdBlock Latitude

### ISSUE THREAD

**Issue by rea987** [Pale-Moon-Addons-Team/adblock-latitude#13]
Hi all,

I am not sure if I am asking too much but I would like to suggest/request a feature for Adblock Latitude. AdBlock (not Adblock Plus) has a nice feature to allow users to whitelist specific YouTube channel. Thanks to that feature users can support the channels they like by allowing the ads without bothering to disable the extension for every video. Unfortunately AdBlock is currently available only for Mozilla Firefox and Google Chrome. As it seem, developers do not consider Pale Moon due to Add-on SDK incompatibility. I wonder if that would be possible to add YouTube channel whitelisting feature to Adblock Latitude. Thank you.

http://support.getadblock.com/discussions/suggestions/7631-other-browsers

AdBlock:
https://getadblock.com/

Whitelisting a YouTube channel:
http://support.getadblock.com/kb/other-problems/how-do-i-whitelist-a-specific-youtube-channel

Source code of the extension:
http://code.getadblock.com/
http://code.getadblock.com/releases/

![ekrangoruntusu-totalbiscuit the cynical brit - youtube - mozilla firefox](https://cloud.githubusercontent.com/assets/1547646/9281298/c41ad69a-42cc-11e5-8985-94d979320efc.png)

**Comment by mattatobin** [comment]
I already answered that here: https://forum.palemoon.org/viewtopic.php?f=16&t=9142&p=61496#p61496
