### ISSUE TITLE
[v3.5.0 branch] Loading of blocked content on PM start (continued)

### ISSUE THREAD

**Issue by nelegalno** [Pale-Moon-Addons-Team/adblock-latitude#18]
Dear Mr. Tobin,
since you obviously have misunderstood my previous questions and have locked the issue ( Ref #17 ) I can't respond to you there and have no other option than to open a new one.

One) The whole question was intended to be about the 3.5.0b1 version - for some reason it seems you thought it was for the v3.0.X one for witch I apologize (I'll try to be more clear in the future). Also I have seen multiple mentions of the "backed out due to issues" but never have seen the issues in question or an explanation what they are and I've been using that feature since Nov 2014.

Two) You'll have to excuse me but after seeing the text "***Adblock Latitude has also been configured to allow some non-intrusive advertising.***" in https://github.com/Pale-Moon-Addons-Team/adblock-latitude/blob/3.5_TRUNK/src/locale/en-US/firstRun.dtd#L17 I believe my question was reasonable. Again please accept my apologies for not making it clear I was speaking about v3.5.0b1.

Three) Thanks for the answer, would you consider adding a line somewhere (for example in a *README.md* in the 3.5_TRUNK branch or https://addons.palemoon.org/extensions/privacy-and-security/adblock-latitude/ ) until the next version so others won't have to ask the same question.

**"AS FOR THE MAIN ISSUE for which this bug is titled. This is a complete WONTFIX for 3.0.x versions."** - the issue was never intended for v3.0.X and I believe it was made clear in issue #1 that you don't intend to fix the problem in the v3.0 branch.
**"3.5 sidesteps the issue entirely ..."** - great news, can't wait for the v3.5.0b2 version to test it.

**"So I am closing this bug as WONTFIX."** - what's the rush? Can't you wait for the other side to read the answers and respond or close the issue?

**"Also, DUPLICATE of Issue #1"** - no actually it isn't a duplicate although it's definitely related to it.

**Comment by mattatobin** [comment]
firstRun.dtd.. Yeah Localization files need cleaned up badly. Don't worry.. they are unused strings.

As for the behavior you describe.. it is NOT present in 3.5. ABL 3.5 literally loads everything before the browser window is even created so all filtering is totally engaged and ready to do it's thing before the page even loads.

**Comment by nelegalno** [comment]
Good to know it's just an unused line.
I'll check the rest once I have some more free time.
I didn't assume but I'm still eager to test it on a portable copy of PM - just in case something goes wrong.
