### ISSUE TITLE
Migrate prefs and use own data folder.

### ISSUE THREAD

**Issue by wolfbeast** [Pale-Moon-Addons-Team/adblock-latitude#2]
Desired enhancement:

* Have ABL store preferences and data in a unique pref tree and data folder, respectively.
* Have ABL examine and import ABP and ABE preferences. We'll have to think about what to do when both are found - always prioritize one over the other?

**Comment by mattatobin** [comment]
This should be accomplished by leveraging the functionality of the patterns.ini import/export. Just need to offer a small UI to grab it from profile\adblockplus\patterns.ini or profile\adblockedge\patterns.ini

There really aren't any other preferences of importance to migrate over.

**Comment by mattatobin** [comment]
This was partly completed by 36cf454a39014b16855329b08628b1b3005ffbda

**Comment by mattatobin** [comment]
It has been decided the best course of action is to retrofit a solution into the current generation of ABL to facilitate the future transition.

Namely when filter preferences are flushed to disk flush them to [profile]/adblockplus AND [profile]/adblocklatitude

Target Release Adblock Latitude 3.0.3

**Comment by mattatobin** [comment]
Sidestepped due to 54f835113b8a4258e812c15f3228015a23642967 .. Will revisit one day..
