### ISSUE TITLE
Having too many custom element hiding rules breaks site CSS

### ISSUE THREAD

**Issue by MikeRosoft** [Pale-Moon-Addons-Team/adblock-latitude#23]
The Czech news website https://www.novinky.cz/ rather aggressively places ads on its pages; in addition, it uses dynamic element ids and URLs. Fighting this requires extensive filtering; most elements need to be hidden rather than blocked.

I subscribe to [EasyList](https://easylist-downloads.adblockplus.org/easylist.txt) and [EasyList Czech+Slovak](https://easylist-downloads.adblockplus.org/easylistczechslovak+easylist.txt). In addition, I have numerous filters specifically for this site:

```
novinky.cz##DIV[style^="position: absolute;"]
novinky.cz###adSkyBottomWrapper
novinky.cz###rightColumn
novinky.cz###middleLdrBox
novinky.cz###exchange
novinky.cz##.ban
novinky.cz##.cont
novinky.cz###komercni
novinky.cz###container-eta
novinky.cz##.jeban
novinky.cz##IFRAME[class^="gojkuln"]
||novinky.cz/*/sos/*$image
||novinky.cz/*/DYNBAN/rcdarky/*$subdocument,image
||novinky.cz/*/novinky_leader/*$subdocument,image
||novinky.cz/*/im/dynamic/*
```

(Some of these filters may be redundant to ones in "EasyList Czech+Slovak".)

Now when I access www.novinky.cz, the page initially displays correctly, but after about a second the styles break down and the site displays as if it had no CSS. The console displays an error above: "Style sheet could not be loaded". Disabling AdBlock, or disabling all custom element hiding rules for novinky.cz removes the error.

I also encounter the same bug with Firefox at work. There, I use the last version of Firefox which supports old-style extensions, and Adblock Plus 2.9.1 (with similar filters).

**Comment by wolfbeast** [comment]
Can you please check the effect of your custom rules, i.e.: find which rule(s) in particular cause this issue for you?

**Comment by MikeRosoft** [comment]
It seems that hiding <iframe> elements causes problems. I am currently at my desktop computer with a slightly different configuration. I have the following general hiding rules:

```
###ad-selfpromo
##.obsah-reklamy
##.reklama-obal
##.reklama-clanek
##.reklama-half-page-ad
##.reklama-obsah
###ad-cont
###sklikReklama_19976
###lyslider-adblock-holder
###ad-wrapper-right
###ad-wrapper-left
##.cookie-choices-inner
##.komercniSdeleni
##.rs_reklama
###cookieClicker
```
Plus specifically for novinky.cz:
```
||novinky.cz/*/sos/*$image,subdocument
||novinky.cz/*/novinky_sky/*$subdocument
||novinky.cz/*/novinky_pp_iframe/*$subdocument
||novinky.cz/*/novinky_sky_passback/*$subdocument,image
||novinky.cz/*/novinky_square/*$subdocument,image
||novinky.cz/*/html/www.novinky.cz*$subdocument
||novinky.cz/*_zdravi/domodi?*$subdocument
novinky.cz##img[class^=" adform-domevents-click"]
novinky.cz##IMG[style="border: solid 1px #d0d0d0"]
novinky.cz##iframe[style="display: block!important"][frameborder="0"][height="600"][width="300"]
novinky.cz##div[style^="position: fixed;"]
novinky.cz###superBrandingMain
novinky.cz##DIV[style="top:0px; left:0px; position: absolute; width:100%; min-width:989px; height:600px; display:block; z-index:1; overflow:hidden; margin: 0 auto;"]
novinky.cz###animation_container
novinky.cz###middleLdrBox
novinky.cz##.ban
novinky.cz###container-eta
novinky.cz###im-0ac5fd9774dc188
novinky.cz###rightColumn
novinky.cz###komercni
novinky.cz###adTopsponsor
novinky.cz##.cont
novinky.cz##.ppProdukt
novinky.cz##.ppBox
novinky.cz###adNovinkyNativni
novinky.cz##IFRAME
```

As soon as I added the last rule, the page broke. When I disabled it, the styles started working again. (It is interesting that I already had an iframe hiding rule, and the page worked correctly with it.)

I also subscribe to Easylist, Easylist Czech+Slovak, and [Prebake](https://raw.githubusercontent.com/liamja/Prebake/master/obtrusive.txt). (Also [Malware Domains](https://easylist-downloads.adblockplus.org/malwaredomains_full.txt), but I don't think that is really relevant - this list does not supply any hiding rules.)

**Comment by wolfbeast** [comment]
Blanket-blocking all iframe elements clearly doesn't work for that site (I'd expect it to break many current sites, actually, because iframes are used everywhere) most likely because it dynamically writes out iframes from JavaScript as well as having some static ones. **You need to make your rules more specific.** Why exactly it loses its styling is unclear (and I don't think anyone here has the spare time to try and reverse-engineer this).

This isn't a bug in the extension; it does exactly what it is supposed to do.

**Comment by MikeRosoft** [comment]
For the record, I have discovered which filter was responsible in the original report. It is:
`novinky.cz###exchange`

I have also discovered that hiding the element using Stylish:
`div#exchange { display: none !important; }`
also breaks the page styles. (No idea why this happens.)
