### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by Achaean** [Pale-Moon-Addons-Team/adblock-latitude#24]
Hi! :-)

It's > 1 year without updates and seems that it lost it's efficiency.

**Comment by mattatobin** [comment]
Is there something that needs updated?

**Comment by Achaean** [comment]
It means that whether Latitude is loaded or not the ads finding their way to the screen.
I don't know though what changed on ads strategy behaviour.
Loading another ad blocker (namely UBlock Origins) cuts the ads off.

**Comment by wolfbeast** [comment]
You should simply adjust your subscriptions if the default doesn't work well for the sites you visit. That has very little to do with the way the extension does its job or how often it's updated.

**Comment by Achaean** [comment]
OK! Sounds quite reasonable to me.

I'm closing this report (since this issue isn't related to the addon, but rather to the lists), but consider it as a feature request:
As the rest of adblockers do:
1) Adding optional lists, should be an easier task.
2) Also localized lists should be autoadded.

**Comment by wolfbeast** [comment]
I suggest you explore the extension's option a bit.
![ablfiltersubscriptions1](https://user-images.githubusercontent.com/3359132/37134921-a2de6eee-2292-11e8-9e6f-3095162b0655.png)

**Comment by Achaean** [comment]
I played a bit with them, but I'm facing a problem:
Every time I closing Palemoon, Adblock losing it's subscriptions.
Next time I start Palemoon, Adblock has only the default (EasyList) subscription and the rest are gone.
