### ISSUE TITLE
Not understanding $webrtc and $csp

### ISSUE THREAD

**Issue by lambic12** [Pale-Moon-Addons-Team/adblock-latitude#26]
Hello, 
First of all, thanks for the work on this addon!
There are new filter options created by ABP in 2018 : $webrtc and $csp, maybe a few others.
Lists like easylist are starting to use them, but the lines are not recognized by Adblock Latitude for the moment. Then the filters are not interpreted at all.

**Comment by wolfbeast** [comment]
- WebRTC isn't supported by Pale Moon, so any rules specific for it can safely be ignored
- CSP isn't content; what good would having CSP blocklists do apart from blocking essential security policies there to protect the user from XSS?

**Comment by lambic12** [comment]
- Ok for WebRTC, indeed
- CSP is, for example, the only way to block inline javascripts in a page with an ABP rule. I guess this option has been introduced because more and more sites are dynamically creating obfuscated javascripts inline...

**Comment by wolfbeast** [comment]
I don't think adding CSP rules to received page headers for inline JS is in any way in line with Adblock Latitude's goals and falls outside of its scope of ad blocking. If you need a script blocker, I suggest to look into the realm of uMatrix and the like, and not here.
General adblock lists like Easylist should also not incorporate such rules; if they do then that is IMHO also going outside of their scope.
