### ISSUE TITLE
Locales need to be updated and included

### ISSUE THREAD

**Issue by mattatobin** [Pale-Moon-Addons-Team/adblock-latitude#8]
Right now only the en-US locale is included and updated.

For 3.5.0 we want at least: British English, Spanish, French, and German
For the future we want to complete all more or less Latin based languages.

It would also be nice to have ALL locales updated but we have to be realistic here..

**Comment by wolfbeast** [comment]
Locales can be included as-they-are-completed in extensions.
I'd suggest tossing this one up on BabelZilla.

**Comment by mattatobin** [comment]
I need to clean up en-US a little bit first but that I suppose will be what can be done..
